/**
 * Runtime IPC argument schemas (#143).
 * Each entry is a Zod tuple matching ipcRenderer.invoke arity.
 * Extend this map as more channels migrate to `handleValidated`.
 */

import { z } from "zod";
import { IPC } from "../ipc";
import { isServerProfilePatch } from "../server-profile";
import {
  appDataFolderKindSchema,
  backupCleanupOptionsSchema,
  backupDiskAlertSettingsSchema,
  backupKindSchema,
  backupPolicyWriteSchema,
  restoreBackupOptionsSchema,
  cloneWithParamsSchema,
  clusterIdSchema,
  clusterIniFileSelectionSchema,
  iniFileKeySchema,
  installationServersModeSchema,
  ipcTuple,
  logCleanupOptionsSchema,
  logFileNameSchema,
  logRetentionSettingsSchema,
  modsSearchOptionsSchema,
  nonEmptyStringSchema,
  plainObjectSchema,
  pickPathKindSchema,
  playerKeySchema,
  rconCommandTextSchema,
  serverIdSchema,
  serverIniPayloadSchema,
  startServerOptionsSchema,
  steamCmdCacheKindSchema,
  uiDensitySchema,
  windowsAbsPathSchema,
  MAX_BACKUP_ID_LENGTH,
  MAX_BACKUP_IDS_PER_REQUEST,
  MAX_MOD_IDS_PER_REQUEST,
  MAX_MOD_QUERY_LENGTH,
  MAX_PATH_LENGTH,
  MAX_STRING_PARAM_LENGTH,
  MAX_URL_LENGTH,
} from "./primitives";

const serverProfilePatchSchema = z.custom<unknown>(
  (value) => isServerProfilePatch(value),
  { message: "Invalid server profile patch" },
);

/** Channels registered with `handleValidated` — keep in sync with ipc-handlers. */
export const VALIDATED_IPC_CHANNELS = [
  // Wave 1 — high-risk lifecycle / FS / RCON command / core backups
  IPC.serversCreate,
  IPC.serversUpdate,
  IPC.serversUpdatePatch,
  IPC.serversSetEnabled,
  IPC.serversDelete,
  IPC.serversClone,
  IPC.serversCloneWithParams,
  IPC.serversProbeImport,
  IPC.serversImportExisting,
  IPC.serversStart,
  IPC.serversStop,
  IPC.serversRestart,
  IPC.serversKill,
  IPC.serversInstallFiles,
  IPC.serversUpdateNow,
  IPC.serversVerifyFiles,
  IPC.serversMoveInstall,
  IPC.serversMoveInstallCancel,
  IPC.serversMoveInstallCleanup,
  IPC.serversMoveInstallDismissCleanup,
  IPC.serversOpenFolder,
  IPC.serversOpenNativeTerminal,
  IPC.steamcmdSetPath,
  IPC.steamcmdOpenCache,
  IPC.steamcmdClearCache,
  IPC.rconCommand,
  IPC.pickPath,
  IPC.appOpenDataFolder,
  IPC.backupsDelete,
  IPC.backupsDeleteFailed,
  IPC.backupsRestore,
  IPC.backupsImport,
  IPC.backupsRunCleanup,
  // Wave 2 — remaining mutating / path / string-heavy channels
  IPC.serversInstallation,
  IPC.steamcmdInstall,
  IPC.steamcmdCancel,
  IPC.steamcmdConsole,
  IPC.criticalJobRetry,
  IPC.criticalJobDismiss,
  IPC.criticalJobCancel,
  IPC.rconRetryConnection,
  IPC.rconGetStatus,
  IPC.rconTabFocusChanged,
  IPC.refreshPlayerList,
  IPC.kickPlayer,
  IPC.banPlayer,
  IPC.listBannedPlayers,
  IPC.unbanPlayer,
  IPC.openBanListFile,
  IPC.eventsRecent,
  IPC.appSetUiDensity,
  IPC.appSetCloseWindowToTray,
  IPC.appSetStartWithWindows,
  IPC.appSetTrayCloseHintDismissed,
  IPC.appCheckForUpdate,
  IPC.appDownloadUpdate,
  IPC.appInstallUpdate,
  IPC.appOpenYarkReleaseNotes,
  IPC.iniRead,
  IPC.iniOpenInEditor,
  IPC.iniPreview,
  IPC.iniSave,
  IPC.clusterIniGet,
  IPC.clusterIniGetOrDraft,
  IPC.clusterIniPreview,
  IPC.clusterIniSave,
  IPC.clusterIniDelete,
  IPC.clusterIniPreviewRestore,
  IPC.clusterIniPreviewPromote,
  IPC.clusterIniPreviewSeed,
  IPC.clusterIniRestore,
  IPC.clusterIniPromote,
  IPC.clusterIniSeed,
  IPC.configTransferDescribe,
  IPC.configTransferPreview,
  IPC.configTransferCommit,
  IPC.logsList,
  IPC.logsRuntime,
  IPC.logsReadUpdate,
  IPC.logsExport,
  IPC.logsOpenUpdateFile,
  IPC.logsClearEvents,
  IPC.logsClearRuntime,
  IPC.logsDeleteUpdate,
  IPC.logsClearUpdates,
  IPC.logsSetRetentionSettings,
  IPC.logsPreviewCleanup,
  IPC.logsRunCleanup,
  IPC.modsGet,
  IPC.modsGetMany,
  IPC.modsSearch,
  IPC.modsGetByReference,
  IPC.modsOpenCurseForge,
  IPC.backupsList,
  IPC.backupsCreate,
  IPC.backupsGetPolicy,
  IPC.backupsSetPolicy,
  IPC.backupsResolveRoot,
  IPC.backupsOpenFolder,
  IPC.backupsOpenRoot,
  IPC.backupsExport,
  IPC.backupsDismissFleetAlert,
  IPC.backupsSetDiskAlertSettings,
  IPC.backupsPreviewCleanup,
  // Wave 3 — remaining read-only / zero-arg invokes
  IPC.serversList,
  IPC.serversStatuses,
  IPC.clusterCheck,
  IPC.steamcmdStatus,
  IPC.rconGetAllStatus,
  IPC.appListDataFolders,
  IPC.appGetUiDensity,
  IPC.appGetDesktopShellPreferences,
  IPC.appGetUpdateStatus,
  IPC.logsGetRetentionSettings,
  IPC.backupsFleetSummary,
  IPC.backupsGetDiskAlertSettings,
] as const;

export type ValidatedIpcChannel = (typeof VALIDATED_IPC_CHANNELS)[number];

export const ipcArgSchemas = {
  [IPC.serversList]: z.tuple([]),
  [IPC.serversCreate]: z.tuple([plainObjectSchema]),
  [IPC.serversUpdate]: z.tuple([serverIdSchema, plainObjectSchema]),
  [IPC.serversUpdatePatch]: z.tuple([serverIdSchema, serverProfilePatchSchema]),
  [IPC.serversSetEnabled]: z.tuple([serverIdSchema, z.boolean()]),
  [IPC.serversDelete]: z.tuple([
    serverIdSchema,
    z.object({
      deleteInstallFiles: z.boolean(),
      requireEmptyInstall: z.boolean().optional(),
    }),
  ]),
  [IPC.serversClone]: z.tuple([serverIdSchema]),
  [IPC.serversCloneWithParams]: z.tuple([serverIdSchema, cloneWithParamsSchema]),
  [IPC.serversProbeImport]: z.tuple([windowsAbsPathSchema]),
  [IPC.serversImportExisting]: z.tuple([plainObjectSchema]),
  [IPC.serversStart]: ipcTuple(serverIdSchema, startServerOptionsSchema.nullish()),
  [IPC.serversStop]: z.tuple([serverIdSchema]),
  [IPC.serversRestart]: ipcTuple(serverIdSchema, startServerOptionsSchema.nullish()),
  [IPC.serversKill]: z.tuple([serverIdSchema]),
  [IPC.serversInstallFiles]: z.tuple([serverIdSchema]),
  [IPC.serversUpdateNow]: z.tuple([serverIdSchema]),
  [IPC.serversVerifyFiles]: z.tuple([serverIdSchema]),
  [IPC.serversMoveInstall]: z.tuple([serverIdSchema, windowsAbsPathSchema]),
  [IPC.serversMoveInstallCancel]: z.tuple([]),
  [IPC.serversMoveInstallCleanup]: z.tuple([serverIdSchema, windowsAbsPathSchema]),
  [IPC.serversMoveInstallDismissCleanup]: z.tuple([serverIdSchema]),
  [IPC.serversOpenFolder]: z.tuple([serverIdSchema]),
  [IPC.serversOpenNativeTerminal]: z.tuple([serverIdSchema]),
  [IPC.serversStatuses]: z.tuple([]),
  [IPC.serversInstallation]: ipcTuple(
    z.boolean().nullish(),
    installationServersModeSchema.nullish(),
  ),
  [IPC.steamcmdStatus]: z.tuple([]),
  [IPC.steamcmdSetPath]: z.tuple([windowsAbsPathSchema]),
  [IPC.steamcmdOpenCache]: z.tuple([steamCmdCacheKindSchema]),
  [IPC.steamcmdClearCache]: z.tuple([steamCmdCacheKindSchema]),
  [IPC.steamcmdInstall]: z.tuple([]),
  [IPC.steamcmdCancel]: z.tuple([]),
  [IPC.steamcmdConsole]: ipcTuple(z.number().int().positive().max(10_000).nullish()),
  [IPC.criticalJobRetry]: z.tuple([nonEmptyStringSchema("Critical job id")]),
  [IPC.criticalJobDismiss]: z.tuple([nonEmptyStringSchema("Critical job id")]),
  [IPC.criticalJobCancel]: z.tuple([nonEmptyStringSchema("Critical job id")]),
  [IPC.clusterCheck]: z.tuple([]),
  [IPC.rconCommand]: z.tuple([serverIdSchema, rconCommandTextSchema]),
  [IPC.rconRetryConnection]: z.tuple([serverIdSchema]),
  [IPC.rconGetStatus]: z.tuple([serverIdSchema]),
  [IPC.rconGetAllStatus]: z.tuple([]),
  [IPC.rconTabFocusChanged]: z.tuple([serverIdSchema, z.boolean()]),
  [IPC.refreshPlayerList]: z.tuple([serverIdSchema]),
  [IPC.kickPlayer]: z.tuple([serverIdSchema, playerKeySchema]),
  [IPC.banPlayer]: z.tuple([serverIdSchema, playerKeySchema]),
  [IPC.listBannedPlayers]: z.tuple([serverIdSchema]),
  [IPC.unbanPlayer]: z.tuple([serverIdSchema, playerKeySchema]),
  [IPC.openBanListFile]: z.tuple([serverIdSchema]),
  [IPC.eventsRecent]: z.tuple([z.number().int().positive().max(5_000)]),
  [IPC.pickPath]: ipcTuple(
    pickPathKindSchema,
    z.string().max(MAX_PATH_LENGTH).nullish(),
    z.string().max(MAX_STRING_PARAM_LENGTH).nullish(),
  ),
  [IPC.appListDataFolders]: z.tuple([]),
  [IPC.appOpenDataFolder]: z.tuple([appDataFolderKindSchema]),
  [IPC.appGetUiDensity]: z.tuple([]),
  [IPC.appSetUiDensity]: z.tuple([uiDensitySchema]),
  [IPC.appGetDesktopShellPreferences]: z.tuple([]),
  [IPC.appSetCloseWindowToTray]: z.tuple([z.boolean()]),
  [IPC.appSetStartWithWindows]: z.tuple([z.boolean()]),
  [IPC.appSetTrayCloseHintDismissed]: z.tuple([z.boolean()]),
  [IPC.appGetUpdateStatus]: z.tuple([]),
  [IPC.appCheckForUpdate]: z.tuple([]),
  [IPC.appDownloadUpdate]: z.tuple([]),
  [IPC.appInstallUpdate]: z.tuple([]),
  [IPC.appOpenYarkReleaseNotes]: z.tuple([]),
  [IPC.iniRead]: z.tuple([serverIdSchema]),
  [IPC.iniOpenInEditor]: z.tuple([serverIdSchema, iniFileKeySchema]),
  [IPC.iniPreview]: z.tuple([serverIdSchema, serverIniPayloadSchema]),
  [IPC.iniSave]: z.tuple([serverIdSchema, serverIniPayloadSchema]),
  [IPC.clusterIniGet]: z.tuple([clusterIdSchema]),
  [IPC.clusterIniGetOrDraft]: z.tuple([clusterIdSchema]),
  [IPC.clusterIniPreview]: z.tuple([clusterIdSchema, serverIniPayloadSchema]),
  [IPC.clusterIniSave]: z.tuple([clusterIdSchema, serverIniPayloadSchema]),
  [IPC.clusterIniDelete]: z.tuple([clusterIdSchema]),
  [IPC.clusterIniPreviewRestore]: ipcTuple(
    clusterIdSchema,
    serverIdSchema,
    clusterIniFileSelectionSchema.nullish(),
  ),
  [IPC.clusterIniPreviewPromote]: ipcTuple(
    clusterIdSchema,
    serverIdSchema,
    clusterIniFileSelectionSchema.nullish(),
  ),
  [IPC.clusterIniPreviewSeed]: ipcTuple(
    clusterIdSchema,
    serverIdSchema,
    clusterIniFileSelectionSchema.nullish(),
  ),
  [IPC.clusterIniRestore]: ipcTuple(
    clusterIdSchema,
    serverIdSchema,
    clusterIniFileSelectionSchema.nullish(),
  ),
  [IPC.clusterIniPromote]: ipcTuple(
    clusterIdSchema,
    serverIdSchema,
    clusterIniFileSelectionSchema.nullish(),
  ),
  [IPC.clusterIniSeed]: ipcTuple(
    clusterIdSchema,
    serverIdSchema,
    clusterIniFileSelectionSchema.nullish(),
  ),
  [IPC.configTransferDescribe]: z.tuple([serverIdSchema]),
  [IPC.configTransferPreview]: z.tuple([
    serverIdSchema,
    serverIdSchema,
    plainObjectSchema,
  ]),
  [IPC.configTransferCommit]: z.tuple([
    serverIdSchema,
    serverIdSchema,
    plainObjectSchema,
    nonEmptyStringSchema("Fingerprint", MAX_STRING_PARAM_LENGTH),
  ]),
  [IPC.logsList]: z.tuple([serverIdSchema]),
  [IPC.logsRuntime]: ipcTuple(
    serverIdSchema,
    z.number().int().positive().max(50_000).nullish(),
  ),
  [IPC.logsReadUpdate]: ipcTuple(
    serverIdSchema,
    logFileNameSchema,
    z.number().int().positive().max(5_000_000).nullish(),
  ),
  [IPC.logsExport]: z.tuple([serverIdSchema]),
  [IPC.logsOpenUpdateFile]: z.tuple([serverIdSchema, logFileNameSchema]),
  [IPC.logsClearEvents]: z.tuple([serverIdSchema]),
  [IPC.logsClearRuntime]: z.tuple([serverIdSchema]),
  [IPC.logsDeleteUpdate]: z.tuple([serverIdSchema, logFileNameSchema]),
  [IPC.logsClearUpdates]: z.tuple([serverIdSchema]),
  [IPC.logsGetRetentionSettings]: z.tuple([]),
  [IPC.logsSetRetentionSettings]: z.tuple([logRetentionSettingsSchema]),
  [IPC.logsPreviewCleanup]: ipcTuple(logCleanupOptionsSchema.nullish()),
  [IPC.logsRunCleanup]: ipcTuple(logCleanupOptionsSchema.nullish()),
  [IPC.modsGet]: ipcTuple(
    nonEmptyStringSchema("Mod id", 64),
    z.boolean().nullish(),
  ),
  [IPC.modsGetMany]: ipcTuple(
    z.array(nonEmptyStringSchema("Mod id", 64)).max(MAX_MOD_IDS_PER_REQUEST),
    z.boolean().nullish(),
  ),
  [IPC.modsSearch]: ipcTuple(
    z.string().max(MAX_MOD_QUERY_LENGTH),
    modsSearchOptionsSchema.nullish(),
  ),
  [IPC.modsGetByReference]: z.tuple([
    nonEmptyStringSchema("Mod reference", MAX_STRING_PARAM_LENGTH),
  ]),
  [IPC.modsOpenCurseForge]: z.tuple([
    nonEmptyStringSchema("CurseForge URL", MAX_URL_LENGTH),
  ]),
  [IPC.backupsList]: ipcTuple(
    serverIdSchema,
    z.number().int().positive().max(5_000).nullish(),
  ),
  [IPC.backupsCreate]: ipcTuple(
    serverIdSchema,
    z.array(backupKindSchema).max(3).nullish(),
  ),
  [IPC.backupsDelete]: z.tuple([
    serverIdSchema,
    z
      .array(nonEmptyStringSchema("Backup id", MAX_BACKUP_ID_LENGTH))
      .max(MAX_BACKUP_IDS_PER_REQUEST),
  ]),
  [IPC.backupsDeleteFailed]: z.tuple([serverIdSchema, backupKindSchema]),
  [IPC.backupsRestore]: ipcTuple(
    serverIdSchema,
    nonEmptyStringSchema("Backup id", MAX_BACKUP_ID_LENGTH),
    restoreBackupOptionsSchema.nullish(),
  ),
  [IPC.backupsGetPolicy]: z.tuple([serverIdSchema]),
  [IPC.backupsSetPolicy]: z.tuple([serverIdSchema, backupPolicyWriteSchema]),
  [IPC.backupsResolveRoot]: z.tuple([serverIdSchema]),
  [IPC.backupsOpenFolder]: z.tuple([
    serverIdSchema,
    nonEmptyStringSchema("Backup id", MAX_BACKUP_ID_LENGTH),
  ]),
  [IPC.backupsOpenRoot]: z.tuple([serverIdSchema]),
  [IPC.backupsExport]: z.tuple([
    serverIdSchema,
    nonEmptyStringSchema("Backup id", MAX_BACKUP_ID_LENGTH),
    windowsAbsPathSchema,
  ]),
  [IPC.backupsImport]: z.tuple([
    serverIdSchema,
    backupKindSchema,
    windowsAbsPathSchema,
  ]),
  [IPC.backupsFleetSummary]: z.tuple([]),
  [IPC.backupsDismissFleetAlert]: z.tuple([
    nonEmptyStringSchema("Alert id"),
    nonEmptyStringSchema("Fingerprint"),
  ]),
  [IPC.backupsGetDiskAlertSettings]: z.tuple([]),
  [IPC.backupsSetDiskAlertSettings]: z.tuple([backupDiskAlertSettingsSchema]),
  [IPC.backupsPreviewCleanup]: z.tuple([backupCleanupOptionsSchema]),
  [IPC.backupsRunCleanup]: z.tuple([backupCleanupOptionsSchema]),
} as const satisfies Record<ValidatedIpcChannel, z.ZodTypeAny>;
