/**
 * Runtime IPC argument schemas (#143).
 * Each entry is a Zod tuple matching ipcRenderer.invoke arity.
 * Extend this map as more channels migrate to `handleValidated`.
 */

import { z } from "zod";
import { IPC } from "../ipc";
import { DISCORD_MESSAGE_MAX_LENGTH } from "../settings/discord-webhook";
import { onboardingRecordSchema } from "../settings/onboarding";
import {
  HOSTED_RESOURCES_MAX_CONTENT_BYTES,
  HOSTED_RESOURCES_MAX_NOTES_LENGTH,
  HOSTED_RESOURCES_MAX_PORT,
  HOSTED_RESOURCES_MIN_PORT,
  HOSTED_RESOURCES_MAX_TAG_LENGTH,
  HOSTED_RESOURCES_MAX_TAGS,
} from "../settings/hosted-resources";
import { isServerProfilePatch } from "../server/server-profile";
import {
  appDataFolderKindSchema,
  appearanceSettingsSchema,
  backupCleanupOptionsSchema,
  backupDiskAlertSettingsSchema,
  backupKindSchema,
  backupPolicyWriteSchema,
  maintenancePolicyWriteSchema,
  restoreBackupOptionsSchema,
  cloneWithParamsSchema,
  clusterIdSchema,
  clusterIniFileSelectionSchema,
  crashRecoveryPolicyWriteSchema,
  iniFileKeySchema,
  installationServersModeSchema,
  ipcTuple,
  logCleanupOptionsSchema,
  logFileNameSchema,
  logRetentionSettingsSchema,
  modsSearchOptionsSchema,
  asaApiPluginNameSchema,
  nonEmptyStringSchema,
  plainObjectSchema,
  pickPathKindSchema,
  playerKeySchema,
  rconCommandTextSchema,
  serverIdSchema,
  serverIniPayloadSchema,
  startServerOptionsSchema,
  steamCmdCacheKindSchema,
  uiDensitySchema,
  windowsAbsPathSchema,
  MAX_BACKUP_ID_LENGTH,
  MAX_BACKUP_IDS_PER_REQUEST,
  MAX_MOD_IDS_PER_REQUEST,
  MAX_MOD_QUERY_LENGTH,
  MAX_PATH_LENGTH,
  MAX_STRING_PARAM_LENGTH,
  MAX_URL_LENGTH,
} from "./primitives";

const serverProfilePatchSchema = z.custom<unknown>((value) => isServerProfilePatch(value), {
  message: "Invalid server profile patch",
});

/** Channels registered with `handleValidated` — keep in sync with ipc-handlers. */
export const VALIDATED_IPC_CHANNELS = [
  // Wave 1 — high-risk lifecycle / FS / RCON command / core backups
  IPC.serversCreate,
  IPC.serversUpdate,
  IPC.serversUpdatePatch,
  IPC.serversSetEnabled,
  IPC.serversDelete,
  IPC.serversClone,
  IPC.serversCloneWithParams,
  IPC.serversCloneCopyCancel,
  IPC.serversProbeImport,
  IPC.serversImportExisting,
  IPC.serversStart,
  IPC.serversStop,
  IPC.serversRestart,
  IPC.serversKill,
  IPC.serversInstallFiles,
  IPC.serversUpdateNow,
  IPC.serversEnqueueUpdate,
  IPC.serversVerifyFiles,
  IPC.serversMoveInstall,
  IPC.serversMoveInstallCancel,
  IPC.serversMoveInstallCleanup,
  IPC.serversMoveInstallDismissCleanup,
  IPC.serversOpenFolder,
  IPC.serversOpenNativeTerminal,
  IPC.serversAsaApiStatus,
  IPC.serversAsaApiInstall,
  IPC.serversAsaApiUninstall,
  IPC.serversAsaApiSetPluginEnabled,
  IPC.serversAsaApiDeletePlugin,
  IPC.serversAsaApiAddPluginZip,
  IPC.serversAsaApiOpenWin64,
  IPC.serversAsaApiOpenPlugins,
  IPC.serversAsaApiClearCache,
  IPC.steamcmdSetPath,
  IPC.steamcmdOpenCache,
  IPC.steamcmdClearCache,
  IPC.rconCommand,
  IPC.pickPath,
  IPC.appOpenDataFolder,
  IPC.backupsDelete,
  IPC.backupsDeleteFailed,
  IPC.backupsRestore,
  IPC.backupsImport,
  IPC.backupsRunCleanup,
  // Wave 2 — remaining mutating / path / string-heavy channels
  IPC.serversInstallation,
  IPC.steamcmdInstall,
  IPC.steamcmdCancel,
  IPC.steamcmdPause,
  IPC.steamcmdConsole,
  IPC.criticalJobRetry,
  IPC.criticalJobDismiss,
  IPC.criticalJobCancel,
  IPC.criticalJobResume,
  IPC.criticalJobReorder,
  IPC.rconRetryConnection,
  IPC.rconGetStatus,
  IPC.rconTabFocusChanged,
  IPC.processMetricsSetSampling,
  IPC.refreshPlayerList,
  IPC.kickPlayer,
  IPC.banPlayer,
  IPC.listBannedPlayers,
  IPC.unbanPlayer,
  IPC.openBanListFile,
  IPC.getAdminList,
  IPC.setAdminList,
  IPC.validateAdminListUrl,
  IPC.learnAdminListNames,
  IPC.eventsRecent,
  IPC.appSetUiDensity,
  IPC.appSetAppearance,
  IPC.appSetOpenNativeConsole,
  IPC.appSetLastSeenChangelogVersion,
  IPC.appSetOnboarding,
  IPC.appSetCloseWindowToTray,
  IPC.appSetStartWithWindows,
  IPC.appSetTrayCloseHintDismissed,
  IPC.appSetOsNotifyEnabled,
  IPC.appSetOsNotifyCrash,
  IPC.appSetOsNotifySteamCmd,
  IPC.appSetOsNotifyYarkUpdate,
  IPC.appGetDiscordWebhook,
  IPC.appSetDiscordWebhook,
  IPC.appTestDiscordWebhook,
  IPC.appCheckForUpdate,
  IPC.appDownloadUpdate,
  IPC.appInstallUpdate,
  IPC.appOpenYarkReleaseNotes,
  IPC.appQuit,
  IPC.iniRead,
  IPC.iniOpenInEditor,
  IPC.iniPreview,
  IPC.iniSave,
  IPC.clusterIniGet,
  IPC.clusterIniGetOrDraft,
  IPC.clusterIniPreview,
  IPC.clusterIniSave,
  IPC.clusterIniDelete,
  IPC.clusterIniPreviewRestore,
  IPC.clusterIniPreviewPromote,
  IPC.clusterIniPreviewSeed,
  IPC.clusterIniRestore,
  IPC.clusterIniPromote,
  IPC.clusterIniSeed,
  IPC.configTransferDescribe,
  IPC.configTransferPreview,
  IPC.configTransferCommit,
  IPC.logsList,
  IPC.logsRuntime,
  IPC.logsReadUpdate,
  IPC.logsExport,
  IPC.logsOpenUpdateFile,
  IPC.logsClearEvents,
  IPC.logsClearRuntime,
  IPC.logsDeleteUpdate,
  IPC.logsClearUpdates,
  IPC.logsSetRetentionSettings,
  IPC.logsPreviewCleanup,
  IPC.logsRunCleanup,
  IPC.modsGet,
  IPC.modsGetMany,
  IPC.modsSearch,
  IPC.modsListCategories,
  IPC.modsGetByReference,
  IPC.modsOpenCurseForge,
  IPC.backupsList,
  IPC.backupsCreate,
  IPC.backupsGetPolicy,
  IPC.backupsSetPolicy,
  IPC.maintenanceGetPolicy,
  IPC.maintenanceSetPolicy,
  IPC.maintenanceClearSchedulePause,
  IPC.maintenanceRunRestartNow,
  IPC.maintenanceRunRestartWarning,
  IPC.maintenanceRunUpdateNow,
  IPC.maintenanceCancelUpcoming,
  IPC.crashRecoveryGetPolicy,
  IPC.crashRecoverySetPolicy,
  IPC.crashRecoveryResetAttempts,
  IPC.backupsResolveRoot,
  IPC.backupsOpenFolder,
  IPC.backupsOpenRoot,
  IPC.backupsExport,
  IPC.backupsDismissFleetAlert,
  IPC.backupsSetDiskAlertSettings,
  IPC.backupsPreviewCleanup,
  // Wave 3 — remaining read-only / zero-arg invokes
  IPC.serversList,
  IPC.serversStatuses,
  IPC.clusterCheck,
  IPC.steamcmdStatus,
  IPC.rconGetAllStatus,
  IPC.appListDataFolders,
  IPC.appGetUiDensity,
  IPC.appGetAppearance,
  IPC.appGetOpenNativeConsole,
  IPC.appGetLastSeenChangelogVersion,
  IPC.appGetOnboarding,
  IPC.appGetDesktopShellPreferences,
  IPC.appGetUpdateStatus,
  IPC.logsGetRetentionSettings,
  IPC.backupsFleetSummary,
  IPC.backupsGetDiskAlertSettings,
  // Wave 4 — experimental hosted resources (#564)
  IPC.hostedResourcesGetOverview,
  IPC.hostedResourcesSetEnabled,
  IPC.hostedResourcesSetPort,
  IPC.hostedResourcesCreateResource,
  IPC.hostedResourcesPublishContent,
  IPC.hostedResourcesGetContent,
  IPC.hostedResourcesPublishRevision,
  IPC.hostedResourcesRenameResource,
  IPC.hostedResourcesUpdateMetadata,
  IPC.hostedResourcesListRevisions,
  IPC.hostedResourcesSetResourceEnabled,
  IPC.hostedResourcesDeleteResource,
  IPC.hostedResourcesDiagnostics,
] as const;

export type ValidatedIpcChannel = (typeof VALIDATED_IPC_CHANNELS)[number];

export const ipcArgSchemas = {
  [IPC.serversList]: z.tuple([]),
  [IPC.serversCreate]: z.tuple([plainObjectSchema]),
  [IPC.serversUpdate]: z.tuple([serverIdSchema, plainObjectSchema]),
  [IPC.serversUpdatePatch]: z.tuple([serverIdSchema, serverProfilePatchSchema]),
  [IPC.serversSetEnabled]: z.tuple([serverIdSchema, z.boolean()]),
  [IPC.serversDelete]: z.tuple([
    serverIdSchema,
    z.object({
      deleteInstallFiles: z.boolean(),
      requireEmptyInstall: z.boolean().optional(),
    }),
  ]),
  [IPC.serversClone]: z.tuple([serverIdSchema]),
  [IPC.serversCloneWithParams]: z.tuple([serverIdSchema, cloneWithParamsSchema]),
  [IPC.serversCloneCopyCancel]: z.tuple([]),
  [IPC.serversProbeImport]: z.tuple([windowsAbsPathSchema]),
  [IPC.serversImportExisting]: ipcTuple(
    plainObjectSchema,
    z
      .object({
        allowIncompleteInstall: z.boolean().optional(),
      })
      .nullish(),
  ),
  [IPC.serversStart]: ipcTuple(serverIdSchema, startServerOptionsSchema.nullish()),
  [IPC.serversStop]: z.tuple([serverIdSchema]),
  [IPC.serversRestart]: ipcTuple(serverIdSchema, startServerOptionsSchema.nullish()),
  [IPC.serversKill]: z.tuple([serverIdSchema]),
  [IPC.serversInstallFiles]: z.tuple([serverIdSchema]),
  [IPC.serversUpdateNow]: z.tuple([serverIdSchema]),
  [IPC.serversEnqueueUpdate]: z.tuple([serverIdSchema]),
  [IPC.serversVerifyFiles]: z.tuple([serverIdSchema]),
  [IPC.serversMoveInstall]: z.tuple([serverIdSchema, windowsAbsPathSchema]),
  [IPC.serversMoveInstallCancel]: z.tuple([]),
  [IPC.serversMoveInstallCleanup]: z.tuple([serverIdSchema, windowsAbsPathSchema]),
  [IPC.serversMoveInstallDismissCleanup]: z.tuple([serverIdSchema]),
  [IPC.serversOpenFolder]: z.tuple([serverIdSchema]),
  [IPC.serversOpenNativeTerminal]: z.tuple([serverIdSchema]),
  [IPC.serversAsaApiStatus]: z.tuple([serverIdSchema]),
  [IPC.serversAsaApiInstall]: z.tuple([serverIdSchema]),
  [IPC.serversAsaApiUninstall]: z.tuple([serverIdSchema]),
  [IPC.serversAsaApiSetPluginEnabled]: z.tuple([serverIdSchema, asaApiPluginNameSchema, z.boolean()]),
  [IPC.serversAsaApiDeletePlugin]: z.tuple([serverIdSchema, asaApiPluginNameSchema]),
  [IPC.serversAsaApiAddPluginZip]: z.tuple([serverIdSchema]),
  [IPC.serversAsaApiOpenWin64]: z.tuple([serverIdSchema]),
  [IPC.serversAsaApiOpenPlugins]: z.tuple([serverIdSchema]),
  [IPC.serversAsaApiClearCache]: z.tuple([]),
  [IPC.serversStatuses]: z.tuple([]),
  [IPC.serversInstallation]: ipcTuple(z.boolean().nullish(), installationServersModeSchema.nullish()),
  [IPC.steamcmdStatus]: z.tuple([]),
  [IPC.steamcmdSetPath]: z.tuple([windowsAbsPathSchema]),
  [IPC.steamcmdOpenCache]: z.tuple([steamCmdCacheKindSchema]),
  [IPC.steamcmdClearCache]: z.tuple([steamCmdCacheKindSchema]),
  [IPC.steamcmdInstall]: z.tuple([]),
  [IPC.steamcmdCancel]: z.tuple([]),
  [IPC.steamcmdPause]: z.tuple([]),
  [IPC.steamcmdConsole]: ipcTuple(z.number().int().positive().max(10_000).nullish()),
  [IPC.criticalJobRetry]: z.tuple([nonEmptyStringSchema("Critical job id")]),
  [IPC.criticalJobDismiss]: z.tuple([nonEmptyStringSchema("Critical job id")]),
  [IPC.criticalJobCancel]: z.tuple([nonEmptyStringSchema("Critical job id")]),
  [IPC.criticalJobResume]: z.tuple([nonEmptyStringSchema("Critical job id")]),
  [IPC.criticalJobReorder]: z.tuple([nonEmptyStringSchema("Critical job id"), z.enum(["up", "down"])]),
  [IPC.clusterCheck]: z.tuple([]),
  [IPC.rconCommand]: z.tuple([serverIdSchema, rconCommandTextSchema]),
  [IPC.rconRetryConnection]: z.tuple([serverIdSchema]),
  [IPC.rconGetStatus]: z.tuple([serverIdSchema]),
  [IPC.rconGetAllStatus]: z.tuple([]),
  [IPC.rconTabFocusChanged]: z.tuple([serverIdSchema, z.boolean()]),
  [IPC.processMetricsSetSampling]: z.tuple([z.boolean()]),
  [IPC.refreshPlayerList]: z.tuple([serverIdSchema]),
  [IPC.kickPlayer]: z.tuple([serverIdSchema, playerKeySchema]),
  [IPC.banPlayer]: z.tuple([serverIdSchema, playerKeySchema]),
  [IPC.listBannedPlayers]: z.tuple([serverIdSchema]),
  [IPC.unbanPlayer]: z.tuple([serverIdSchema, playerKeySchema]),
  [IPC.openBanListFile]: z.tuple([serverIdSchema]),
  [IPC.getAdminList]: z.tuple([serverIdSchema]),
  [IPC.setAdminList]: z.tuple([
    serverIdSchema,
    z.object({
      adminListUrl: z.string().max(MAX_STRING_PARAM_LENGTH),
      updateAllowedCheatersInterval: z.number().finite(),
    }),
  ]),
  [IPC.validateAdminListUrl]: z.tuple([serverIdSchema, z.string().max(MAX_STRING_PARAM_LENGTH)]),
  [IPC.learnAdminListNames]: z.tuple([
    serverIdSchema,
    z
      .array(
        z.object({
          id: z.string().min(1).max(MAX_STRING_PARAM_LENGTH),
          name: z.string().min(1).max(MAX_STRING_PARAM_LENGTH),
        }),
      )
      .max(500),
  ]),
  [IPC.eventsRecent]: z.tuple([z.number().int().positive().max(5_000)]),
  [IPC.pickPath]: ipcTuple(
    pickPathKindSchema,
    z.string().max(MAX_PATH_LENGTH).nullish(),
    z.string().max(MAX_STRING_PARAM_LENGTH).nullish(),
  ),
  [IPC.appListDataFolders]: z.tuple([]),
  [IPC.appOpenDataFolder]: z.tuple([appDataFolderKindSchema]),
  [IPC.appGetUiDensity]: z.tuple([]),
  [IPC.appSetUiDensity]: z.tuple([uiDensitySchema]),
  [IPC.appGetAppearance]: z.tuple([]),
  [IPC.appSetAppearance]: z.tuple([appearanceSettingsSchema]),
  [IPC.appGetOpenNativeConsole]: z.tuple([]),
  [IPC.appSetOpenNativeConsole]: z.tuple([z.boolean()]),
  [IPC.appGetLastSeenChangelogVersion]: z.tuple([]),
  [IPC.appSetLastSeenChangelogVersion]: z.tuple([nonEmptyStringSchema("App version")]),
  [IPC.appGetOnboarding]: z.tuple([]),
  [IPC.appSetOnboarding]: z.tuple([onboardingRecordSchema.nullable()]),
  [IPC.appGetDesktopShellPreferences]: z.tuple([]),
  [IPC.appSetCloseWindowToTray]: z.tuple([z.boolean()]),
  [IPC.appSetStartWithWindows]: z.tuple([z.boolean()]),
  [IPC.appSetTrayCloseHintDismissed]: z.tuple([z.boolean()]),
  [IPC.appSetOsNotifyEnabled]: z.tuple([z.boolean()]),
  [IPC.appSetOsNotifyCrash]: z.tuple([z.boolean()]),
  [IPC.appSetOsNotifySteamCmd]: z.tuple([z.boolean()]),
  [IPC.appSetOsNotifyYarkUpdate]: z.tuple([z.boolean()]),
  [IPC.appGetDiscordWebhook]: z.tuple([]),
  [IPC.appSetDiscordWebhook]: z.tuple([
    z.object({
      enabled: z.boolean(),
      webhookUrl: z.string().max(MAX_URL_LENGTH),
      events: z.object({
        serverStarted: z.boolean(),
        serverStopped: z.boolean(),
        serverClosedByUser: z.boolean(),
        serverCrashed: z.boolean(),
        updateStarted: z.boolean(),
        updateCompleted: z.boolean(),
        updateFailed: z.boolean(),
      }),
      customMessages: z.record(z.string()).optional(),
    }),
  ]),
  [IPC.appTestDiscordWebhook]: z.tuple([
    z.string().max(MAX_URL_LENGTH),
    z.string().max(DISCORD_MESSAGE_MAX_LENGTH).optional(),
  ]),
  [IPC.appGetUpdateStatus]: z.tuple([]),
  [IPC.appCheckForUpdate]: z.tuple([]),
  [IPC.appDownloadUpdate]: z.tuple([]),
  [IPC.appInstallUpdate]: z.tuple([]),
  [IPC.appOpenYarkReleaseNotes]: z.tuple([]),
  [IPC.appQuit]: z.tuple([]),
  [IPC.iniRead]: z.tuple([serverIdSchema]),
  [IPC.iniOpenInEditor]: z.tuple([serverIdSchema, iniFileKeySchema]),
  [IPC.iniPreview]: z.tuple([serverIdSchema, serverIniPayloadSchema]),
  [IPC.iniSave]: z.tuple([serverIdSchema, serverIniPayloadSchema]),
  [IPC.clusterIniGet]: z.tuple([clusterIdSchema]),
  [IPC.clusterIniGetOrDraft]: z.tuple([clusterIdSchema]),
  [IPC.clusterIniPreview]: z.tuple([clusterIdSchema, serverIniPayloadSchema]),
  [IPC.clusterIniSave]: z.tuple([clusterIdSchema, serverIniPayloadSchema]),
  [IPC.clusterIniDelete]: z.tuple([clusterIdSchema]),
  [IPC.clusterIniPreviewRestore]: ipcTuple(clusterIdSchema, serverIdSchema, clusterIniFileSelectionSchema.nullish()),
  [IPC.clusterIniPreviewPromote]: ipcTuple(clusterIdSchema, serverIdSchema, clusterIniFileSelectionSchema.nullish()),
  [IPC.clusterIniPreviewSeed]: ipcTuple(clusterIdSchema, serverIdSchema, clusterIniFileSelectionSchema.nullish()),
  [IPC.clusterIniRestore]: ipcTuple(clusterIdSchema, serverIdSchema, clusterIniFileSelectionSchema.nullish()),
  [IPC.clusterIniPromote]: ipcTuple(clusterIdSchema, serverIdSchema, clusterIniFileSelectionSchema.nullish()),
  [IPC.clusterIniSeed]: ipcTuple(clusterIdSchema, serverIdSchema, clusterIniFileSelectionSchema.nullish()),
  [IPC.configTransferDescribe]: z.tuple([serverIdSchema]),
  [IPC.configTransferPreview]: z.tuple([serverIdSchema, serverIdSchema, plainObjectSchema]),
  [IPC.configTransferCommit]: z.tuple([
    serverIdSchema,
    serverIdSchema,
    plainObjectSchema,
    nonEmptyStringSchema("Fingerprint", MAX_STRING_PARAM_LENGTH),
  ]),
  [IPC.logsList]: z.tuple([serverIdSchema]),
  [IPC.logsRuntime]: ipcTuple(serverIdSchema, z.number().int().positive().max(50_000).nullish()),
  [IPC.logsReadUpdate]: ipcTuple(
    serverIdSchema,
    logFileNameSchema,
    z.number().int().positive().max(5_000_000).nullish(),
  ),
  [IPC.logsExport]: z.tuple([serverIdSchema]),
  [IPC.logsOpenUpdateFile]: z.tuple([serverIdSchema, logFileNameSchema]),
  [IPC.logsClearEvents]: z.tuple([serverIdSchema]),
  [IPC.logsClearRuntime]: z.tuple([serverIdSchema]),
  [IPC.logsDeleteUpdate]: z.tuple([serverIdSchema, logFileNameSchema]),
  [IPC.logsClearUpdates]: z.tuple([serverIdSchema]),
  [IPC.logsGetRetentionSettings]: z.tuple([]),
  [IPC.logsSetRetentionSettings]: z.tuple([logRetentionSettingsSchema]),
  [IPC.logsPreviewCleanup]: ipcTuple(logCleanupOptionsSchema.nullish()),
  [IPC.logsRunCleanup]: ipcTuple(logCleanupOptionsSchema.nullish()),
  [IPC.modsGet]: ipcTuple(nonEmptyStringSchema("Mod id", 64), z.boolean().nullish()),
  [IPC.modsGetMany]: ipcTuple(
    z.array(nonEmptyStringSchema("Mod id", 64)).max(MAX_MOD_IDS_PER_REQUEST),
    z.boolean().nullish(),
  ),
  [IPC.modsSearch]: ipcTuple(z.string().max(MAX_MOD_QUERY_LENGTH), modsSearchOptionsSchema.nullish()),
  [IPC.modsListCategories]: z.tuple([]),
  [IPC.modsGetByReference]: z.tuple([nonEmptyStringSchema("Mod reference", MAX_STRING_PARAM_LENGTH)]),
  [IPC.modsOpenCurseForge]: z.tuple([nonEmptyStringSchema("CurseForge URL", MAX_URL_LENGTH)]),
  [IPC.backupsList]: ipcTuple(serverIdSchema, z.number().int().positive().max(5_000).nullish()),
  [IPC.backupsCreate]: ipcTuple(serverIdSchema, z.array(backupKindSchema).max(3).nullish()),
  [IPC.backupsDelete]: z.tuple([
    serverIdSchema,
    z.array(nonEmptyStringSchema("Backup id", MAX_BACKUP_ID_LENGTH)).max(MAX_BACKUP_IDS_PER_REQUEST),
  ]),
  [IPC.backupsDeleteFailed]: z.tuple([serverIdSchema, backupKindSchema]),
  [IPC.backupsRestore]: ipcTuple(
    serverIdSchema,
    nonEmptyStringSchema("Backup id", MAX_BACKUP_ID_LENGTH),
    restoreBackupOptionsSchema.nullish(),
  ),
  [IPC.backupsGetPolicy]: z.tuple([serverIdSchema]),
  [IPC.backupsSetPolicy]: z.tuple([serverIdSchema, backupPolicyWriteSchema]),
  [IPC.maintenanceGetPolicy]: z.tuple([serverIdSchema]),
  [IPC.maintenanceSetPolicy]: z.tuple([serverIdSchema, maintenancePolicyWriteSchema]),
  [IPC.maintenanceClearSchedulePause]: z.tuple([serverIdSchema]),
  [IPC.maintenanceRunRestartNow]: z.tuple([serverIdSchema]),
  [IPC.maintenanceRunRestartWarning]: z.tuple([serverIdSchema]),
  [IPC.maintenanceRunUpdateNow]: z.tuple([serverIdSchema]),
  [IPC.maintenanceCancelUpcoming]: z.tuple([serverIdSchema]),
  [IPC.crashRecoveryGetPolicy]: z.tuple([serverIdSchema]),
  [IPC.crashRecoverySetPolicy]: z.tuple([serverIdSchema, crashRecoveryPolicyWriteSchema]),
  [IPC.crashRecoveryResetAttempts]: z.tuple([serverIdSchema]),
  [IPC.backupsResolveRoot]: z.tuple([serverIdSchema]),
  [IPC.backupsOpenFolder]: z.tuple([serverIdSchema, nonEmptyStringSchema("Backup id", MAX_BACKUP_ID_LENGTH)]),
  [IPC.backupsOpenRoot]: z.tuple([serverIdSchema]),
  [IPC.backupsExport]: z.tuple([
    serverIdSchema,
    nonEmptyStringSchema("Backup id", MAX_BACKUP_ID_LENGTH),
    windowsAbsPathSchema,
  ]),
  [IPC.backupsImport]: z.tuple([serverIdSchema, backupKindSchema, windowsAbsPathSchema]),
  [IPC.backupsFleetSummary]: z.tuple([]),
  [IPC.backupsDismissFleetAlert]: z.tuple([nonEmptyStringSchema("Alert id"), nonEmptyStringSchema("Fingerprint")]),
  [IPC.backupsGetDiskAlertSettings]: z.tuple([]),
  [IPC.backupsSetDiskAlertSettings]: z.tuple([backupDiskAlertSettingsSchema]),
  [IPC.backupsPreviewCleanup]: z.tuple([backupCleanupOptionsSchema]),
  [IPC.backupsRunCleanup]: z.tuple([backupCleanupOptionsSchema]),
  [IPC.hostedResourcesGetOverview]: z.tuple([]),
  [IPC.hostedResourcesSetEnabled]: z.tuple([z.boolean()]),
  [IPC.hostedResourcesSetPort]: z.tuple([
    z.number().int().min(HOSTED_RESOURCES_MIN_PORT).max(HOSTED_RESOURCES_MAX_PORT),
  ]),
  [IPC.hostedResourcesCreateResource]: z.tuple([
    z
      .object({
        displayName: nonEmptyStringSchema("Display name", 120),
        format: z.enum(["json", "ini", "text"]),
        content: z.string().max(HOSTED_RESOURCES_MAX_CONTENT_BYTES),
        notes: z.string().max(HOSTED_RESOURCES_MAX_NOTES_LENGTH).optional(),
        tags: z
          .array(z.string().trim().min(1).max(HOSTED_RESOURCES_MAX_TAG_LENGTH))
          .max(HOSTED_RESOURCES_MAX_TAGS)
          .optional(),
      })
      .strict(),
  ]),
  [IPC.hostedResourcesPublishContent]: z.tuple([
    nonEmptyStringSchema("Resource id", 128),
    z.string().max(HOSTED_RESOURCES_MAX_CONTENT_BYTES),
    z
      .object({
        displayName: nonEmptyStringSchema("Display name", 120),
        notes: z.string().max(HOSTED_RESOURCES_MAX_NOTES_LENGTH),
        tags: z.array(z.string().trim().min(1).max(HOSTED_RESOURCES_MAX_TAG_LENGTH)).max(HOSTED_RESOURCES_MAX_TAGS),
      })
      .strict()
      .optional(),
  ]),
  [IPC.hostedResourcesGetContent]: z.tuple([nonEmptyStringSchema("Resource id", 128)]),
  [IPC.hostedResourcesPublishRevision]: z.tuple([
    nonEmptyStringSchema("Resource id", 128),
    nonEmptyStringSchema("Revision id", 128),
  ]),
  [IPC.hostedResourcesRenameResource]: z.tuple([
    nonEmptyStringSchema("Resource id", 128),
    nonEmptyStringSchema("Display name", 120),
  ]),
  [IPC.hostedResourcesUpdateMetadata]: z.tuple([
    nonEmptyStringSchema("Resource id", 128),
    z
      .object({
        displayName: nonEmptyStringSchema("Display name", 120),
        notes: z.string().max(HOSTED_RESOURCES_MAX_NOTES_LENGTH),
        tags: z.array(z.string().trim().min(1).max(HOSTED_RESOURCES_MAX_TAG_LENGTH)).max(HOSTED_RESOURCES_MAX_TAGS),
      })
      .strict(),
  ]),
  [IPC.hostedResourcesListRevisions]: z.tuple([nonEmptyStringSchema("Resource id", 128)]),
  [IPC.hostedResourcesSetResourceEnabled]: z.tuple([nonEmptyStringSchema("Resource id", 128), z.boolean()]),
  [IPC.hostedResourcesDeleteResource]: z.tuple([nonEmptyStringSchema("Resource id", 128)]),
  [IPC.hostedResourcesDiagnostics]: z.tuple([]),
} as const satisfies Record<ValidatedIpcChannel, z.ZodTypeAny>;
